name: Verify tag
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to check"
        required: true
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          TAG_NAME=${{ github.event.inputs.release_tag }}
          REF_NAME=${{ github.ref }}
          REF_TAG=${REF_NAME/refs\/tags\//}

          if [[ "$TAG_NAME" == "$REF_TAG" ]]; then
            echo "The selected tag ($REF_TAG) matches the input tag ($TAG_NAME)."
          else
            echo "The selected tag ($REF_TAG) does not match the input tag ($TAG_NAME). Exiting..."
            exit 1
          fi
      - name: Next step
        run: |
          echo "Success!"
