name: Create Release Tag
run-name: Create Release Tag
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release Tag
        id: create_tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const sha = context.sha
            const repo = context.repo
            const tag_name = `release-${new Date().toISOString()}`
            await github.rest.git.createRef({
              ...repo,
              ref: `refs/tags/${tag_name}`,
              sha: sha
            })
            return tag_name;
      - name: Create Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{ \"tag_name\": \"${{ steps.create_tag.outputs.result }}\", \"name\": \"${{ steps.create_tag.outputs.result }}\", \"body\": \"\"}" \
            https://api.github.com/repos/${{ github.repository }}/releases
